# Generated by Django 5.1.4 on 2025-03-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantages',
            name='subtitle',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
