# Generated by Django 5.1.4 on 2025-03-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_advantages_subtitle_alter_advantages_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='advantages/'),
        ),
    ]
