# Generated by Django 5.1.4 on 2025-03-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_advantages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantages',
            name='color',
            field=models.CharField(default='#6a0dad', max_length=7),
        ),
    ]
