# Generated by Django 5.1.4 on 2025-02-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcategory_options_productcategory_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
