# Generated by Django 5.1.4 on 2025-04-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_favoritesproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritesproduct',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
