# Generated by Django 5.1.4 on 2025-04-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='brand',
        ),
    ]
